In [1]:
import numpy as np
import matplotlib.pyplot as plt

# Exercises 11
## Opg 5

In [2]:
np.set_printoptions(suppress=True)
A = np.array([[6,-3,2],[0, 2, 7], [0, 0, -1]])
np.linalg.det(A)


-12.0

$\lambda_1 = 6, \lambda_2 = 2, \lambda_3 = -1$

In [18]:
l1 = 6
l2 = 2
l3 = -1

In [31]:
Al1I = A - l1 * np.eye(3)
print(Al1I, "\n")

Al1I[0, :] = -(1/3)*Al1I[0, :] 
print(Al1I, "\n")

Al1I[1, :] += 4 * Al1I[0, :] 
print(Al1I, "\n")

Al1I[2, :] += (7/Al1I[1, :][2]) * Al1I[1, :] 
print(Al1I, "\n")

[[ 0. -3.  2.]
 [ 0. -4.  7.]
 [ 0.  0. -7.]] 

[[-0.          1.         -0.66666667]
 [ 0.         -4.          7.        ]
 [ 0.          0.         -7.        ]] 

[[-0.          1.         -0.66666667]
 [ 0.          0.          4.33333333]
 [ 0.          0.         -7.        ]] 

[[-0.          1.         -0.66666667]
 [ 0.          0.          4.33333333]
 [ 0.          0.          0.        ]] 

