# Exercises 6

## 6.1

Reducér

(a) $(AB^{-1})^{-1}A$

$$(AB^{-1})^{-1}A$$
$$=BA^{-1}A$$
$$=BI$$
$$=B$$


(b) $A^{-1}(A^TB)^T$

$$A^{-1}(A^TB)^T$$
$$=A^{-1}B^TA$$

(c) $(AC)^{-1}(ABA^{-1})(AC)$

$$(AC)^{-1}(ABA^{-1})(AC)$$
$$=C^{-1}A^{-1}(ABA^{-1})(AC)$$
$$=C^{-1}(A^{-1}AB)A^{-1}(AC)$$
$$=C^{-1}(IB)A^{-1}(AC)$$
$$=C^{-1}(IB)(A^T)^{-1}A)C$$
$$=C^{-1}BC$$

(d) $(A^{-1}B)^TA^T$

$$(A^{-1}B)^TA^T$$
$$=B^T(A^T)^{-1}A^T$$
$$=B^TI$$
$$=B^T$$


In [1]:
import numpy as np
n = 2
A = np.zeros((n,n))
i = 1
for x in range(n):
    for y in range(n):
        A[x,y] = i * np.sqrt(1/i)
        i+=1;


B = np.zeros((n,n))
i = 1000
for x in range(n):
    for y in range(n):
        B[x,y] = i * 10 / np.sqrt(1/i**0.2) - 17000
        i-=1;

print(np.around(np.linalg.inv(A) @ A @ B.T ,2))

[[2952.62 2908.73]
 [2930.68 2886.79]]


## 6.3
(a)
(b)

In [1]:
import numpy as np

def hhm(x): 
    u = x / np.linalg.norm(x)
    eps = -1 if u[0,0] >= 0 else 1
    s = 1+ np.abs(u[0,0])
    e0 = np.array([1.,0,0])[:, np.newaxis]
    vv = (1/s) * (e0 - eps*u)
    I = np.eye(x.shape[0])
    H = I - s * vv @ vv.T
    return H

In [2]:
hhm(np.array([0.,0,1])[:, np.newaxis])

array([[ 0.,  0., -1.],
       [ 0.,  1.,  0.],
       [-1.,  0.,  0.]])

In [3]:
hhm(np.array([2,1,-2.])[:, np.newaxis]) @ np.array([2,1,-2.])[:, np.newaxis]

array([[-3.00000000e+00],
       [ 5.55111512e-17],
       [-2.22044605e-16]])

In [4]:
hhm(np.array([0.,0,1])[:, np.newaxis]) @ np.array([0.,0,1])[:, np.newaxis]

array([[-1.],
       [ 0.],
       [ 0.]])