# Exercies 4

## Opgave 4.1

Let $A\in \mathbb{R}^{1000\times 70}, B, C \in \mathbb{R}^{70\times3000}, D \in \mathbb{R}^{3000\times3000}$

Note the number of flops for

(a) $AB$

(b) $A(B+C)$

(c) $(CD)A$

(d) $C(DA)$

(e) $(A(BD))A$

(f) $(AB)(DA)$

(g) $A(B(DA))$


In [1]:
import numpy as np

shape1 = (1000,  70)
shape2 = (70,    3000)
shape3 = (3000,  3000)

def shape_of_mult(s1, s2):
    m, n = s1
    n, r = s2
    return (m, r)

def cost_of_mult(s1, s2):
    m, n = s1
    n, r = s2
    return 2*m*n*r

def cost_of_add(s1):
    m, n = s1
    return m*n

In [2]:
# (a) 
print(cost_of_mult(shape1, shape2))

420000000


In [3]:
# (b) 
print(cost_of_mult(shape1, shape2))
print("+")
print(cost_of_add(shape2))
print(cost_of_mult(shape1, shape2) + cost_of_add(shape2))

420000000
+
210000
420210000


In [4]:
# (c) 
print(cost_of_mult(shape2, shape3))
newShape = shape_of_mult(shape2, shape3)
print("+")
print(cost_of_mult(newShape, shape1))

print(cost_of_mult(newShape, shape1) + cost_of_mult(shape2, shape3))

1260000000
+
9800000
1269800000


In [5]:
# (d) 
newShape = shape_of_mult(shape3,shape1)
DA = cost_of_mult (shape3, shape1)
CDA = cost_of_mult(shape2, newShape)

print(DA)
print("+")
print(CDA)
print(DA + CDA)




420000000
+
29400000
449400000


In [6]:
# (e)
newShape1 = shape_of_mult(shape2,shape3) #BD shape
newShape2 = shape_of_mult(shape1,newShape1) #A(BD) shape
BD = cost_of_mult(shape2, shape3)
ABD = cost_of_mult(shape1, newShape1)
ABDA = cost_of_mult(newShape2, shape1)

print(BD)
print("+")
print(ABD)
print("+")
print(ABDA)
print(BD + ABD + ABDA)

1260000000
+
420000000
+
140000000
1820000000


In [7]:
# (f)
newShape1 = shape_of_mult(shape1, shape2) #AB
newShape1 = shape_of_mult(shape3, shape1) #DA
AB = cost_of_mult(shape1, shape2)
DA = cost_of_mult(shape3, shape1)
ABDA = cost_of_mult(newShape1, newShape2)

print(AB)
print("+")
print(DA)
print("+")
print(ABDA)
print("=")
print(AB+DA+ABDA)

420000000
+
420000000
+
18000000000
=
18840000000


In [8]:
#(g)
newShape1 = shape_of_mult(shape3, shape1) # DA
newShape2 = shape_of_mult(shape2, newShape1) # B(DA)

DA = cost_of_mult(shape3, shape1)
BDA = cost_of_mult(shape2, newShape1)
ABDA = cost_of_mult(shape1, newShape2) # A(B(DA))

print(DA)
print("+")
print(BDA)
print("+")
print(ABDA)
print("=")
print(DA+BDA+ABDA)

420000000
+
29400000
+
9800000
=
459200000


## Opgave 4.2

Solve the systems

$$(a)$$
$$2x - 3y = 7$$
$$x + 2y = -2$$

$$(b)$$
$$2x+y-2z=1$$
$$x-2y+z=-1$$
$$2x+4y+2z=0$$

$$(c)$$
$$2x-y+2z=0$$
$$x+y-z=3$$

In [20]:
import numpy as np
m = np.array([[2,-3.,7],[1,2,-2]])

print("a")
print(m)
m[0,:] -= m[1,:]
print(m)
m[1,:] -= m[0,:]
print(m)
m[1,:] = (1./7.) * m[1,:]
print(m)
m[0,:] +=  5 * m[1,:]
print(m)
print(2*4-(-1))

a
[[ 2. -3.  7.]
 [ 1.  2. -2.]]
[[ 1. -5.  9.]
 [ 1.  2. -2.]]
[[  1.  -5.   9.]
 [  0.   7. -11.]]
[[ 1.         -5.          9.        ]
 [ 0.          1.         -1.57142857]]
[[ 1.          0.          1.14285714]
 [ 0.          1.         -1.57142857]]
9


In [43]:
m = np.array([[2,1.,-2,1],[1,-2,1,-1],[2,4,2,0]])

print("a")
print(m)
m[0,:] -= m[1,:]
print(m)
m[1,:] -= m[0,:]
print(m)
m[2,:] -= 2 * m[0,:]
print(m)
m[1,:] = -(1/5) * m[1,:]
print(m)
m[2,:] += 2 * m[1,:]
print(m,"\n")
m[2,:] = (1/6.4) * m[2,:]
print(m)
m[1,:] += 0.8 * m[2,:]
print(m)
m[0,:] += 3 * m[2,:]
print(m)
m[0,:] -= 3 * m[1,:]
print(m)


a
[[ 2.  1. -2.  1.]
 [ 1. -2.  1. -1.]
 [ 2.  4.  2.  0.]]
[[ 1.  3. -3.  2.]
 [ 1. -2.  1. -1.]
 [ 2.  4.  2.  0.]]
[[ 1.  3. -3.  2.]
 [ 0. -5.  4. -3.]
 [ 2.  4.  2.  0.]]
[[ 1.  3. -3.  2.]
 [ 0. -5.  4. -3.]
 [ 0. -2.  8. -4.]]
[[ 1.   3.  -3.   2. ]
 [-0.   1.  -0.8  0.6]
 [ 0.  -2.   8.  -4. ]]
[[ 1.   3.  -3.   2. ]
 [-0.   1.  -0.8  0.6]
 [ 0.   0.   6.4 -2.8]] 

[[ 1.      3.     -3.      2.    ]
 [-0.      1.     -0.8     0.6   ]
 [ 0.      0.      1.     -0.4375]]
[[ 1.      3.     -3.      2.    ]
 [ 0.      1.      0.      0.25  ]
 [ 0.      0.      1.     -0.4375]]
[[ 1.      3.      0.      0.6875]
 [ 0.      1.      0.      0.25  ]
 [ 0.      0.      1.     -0.4375]]
[[ 1.      0.      0.     -0.0625]
 [ 0.      1.      0.      0.25  ]
 [ 0.      0.      1.     -0.4375]]


With your answer on b determine whether or not the system for $a,b,c\in \mathbb{R}$

$$a\begin{bmatrix}2\\1\\2\end{bmatrix} + b\begin{bmatrix}1\\-2\\4\end{bmatrix} + c\begin{bmatrix}-2\\1\\2\end{bmatrix} = a\begin{bmatrix}-1\\1\\0\end{bmatrix}$$