In [1]:
import numpy as np
import matplotlib.pyplot as plt

# Exercises 12

## 12.1 
Done

# 12.2
Kontakt TA for peerwise login

# 12.3
Lad
$u = (1,2,4), v=(-1,2,1)$ og $A = uv^T$

(a) Bestem en basis for $N(A) = \{x\in\mathbb{R}^n | Ax = 0\}$

find $det(A-\lambda I_3)$

$= det(A - \lambda \begin{bmatrix}1 & 0 & 0 \\ 0 & 1 & 0 \\ 0 & 0 & 1\end{bmatrix})$

$ = det( 
\begin{bmatrix}-1 & 2 & 1 \\ -2 & 4 & 2 \\ -4 & 8 & 4\end{bmatrix}
-
\begin{bmatrix}\lambda & 0 & 0 \\ 0 & \lambda & 0 \\ 0 & 0 & \lambda\end{bmatrix}
)$

$ = det( 
\begin{bmatrix}-1-\lambda & 2 & 1 \\ -2 & 4-\lambda & 2 \\ -4 & 8 & 4-\lambda\end{bmatrix}
)$

In [2]:
u = np.array([1,2,4])[:, np.newaxis]
v = np.array([-1,2,1])[:, np.newaxis]
A = u @ v.T
A

array([[-1,  2,  1],
       [-2,  4,  2],
       [-4,  8,  4]])

In [3]:
np.linalg.det(A)

0.0

In [4]:
b = np.zeros(3)[:, np.newaxis]
x = np.linalg.lstsq(A, b, rcond=None)[3][:, np.newaxis]
print(x)

[[1.12249722e+01]
 [4.53246652e-16]
 [1.09476443e-47]]


In [5]:
A @ x

array([[-11.22497216],
       [-22.44994432],
       [-44.89988864]])