In [1]:
import numpy as np
import matplotlib.pyplot as plt

# Exercises 12

## 12.1 
Done

# 12.2
Kontakt TA for peerwise login

# 12.3
Lad
$u = (1,2,4), v=(-1,2,1)$ og $A = uv^T$

(a) Bestem en basis for $N(A) = \{x\in\mathbb{R}^n | Ax = 0\}$

find $det(A-\lambda I_3)$

$= det(A - \lambda \begin{bmatrix}1 & 0 & 0 \\ 0 & 1 & 0 \\ 0 & 0 & 1\end{bmatrix})$

$ = det( 
\begin{bmatrix}-1 & 2 & 1 \\ -2 & 4 & 2 \\ -4 & 8 & 4\end{bmatrix}
-
\begin{bmatrix}\lambda & 0 & 0 \\ 0 & \lambda & 0 \\ 0 & 0 & \lambda\end{bmatrix}
)$

$ = det( 
\begin{bmatrix}-1-\lambda & 2 & 1 \\ -2 & 4-\lambda & 2 \\ -4 & 8 & 4-\lambda\end{bmatrix}
)$

In [2]:
u = np.array([1,2,4])[:, np.newaxis]
v = np.array([-1,2,1])[:, np.newaxis]
A = u @ v.T
A

array([[-1,  2,  1],
       [-2,  4,  2],
       [-4,  8,  4]])

In [3]:
np.linalg.det(A)

0.0

In [4]:
b = np.zeros(3)[:, np.newaxis]
x = np.linalg.lstsq(A, b, rcond=None)[3][:, np.newaxis]
print(x)

[[1.12249722e+01]
 [4.53246652e-16]
 [1.09476443e-47]]


In [5]:
A @ x

array([[-11.22497216],
       [-22.44994432],
       [-44.89988864]])

## 12.5 
Antag at $A=V\Lambda V^-1$ som er diagonaliserbar med egenværdier $\lambda_0, \lambda_1, \lambda_2$. Vis at de følgende matricer er diagonaliserbar og bestem deres egenværdier.

$$
3A = \begin{bmatrix}
    3a_{00} & 3a_{01} & 3a_{02} \\
    3a_{10} & 3a_{11} & 3a_{12} \\
    3a_{20} & 3a_{21} & 3a_{22}
\end{bmatrix}
$$



## 12.6
Let $A=\begin{bmatrix} -1 & 2 \\ 2 & -1 \end{bmatrix}$

$$det(A)=2\cdot 2 + -1 \cdot -1$$
$$=4 + 1 = 5$$
$$
(A - \lambda I_2)v = 0
$$
$$
(\begin{bmatrix} -1 & 2 \\ 2 & -1 \end{bmatrix} - \begin{bmatrix} \lambda & 0\\ 0 & \lambda \end{bmatrix})\begin{bmatrix}v_0 \\ v_0\end{bmatrix} = 0
$$
$$
\begin{bmatrix} -1-\lambda & 2 \\ 2 & -1-\lambda \end{bmatrix}\begin{bmatrix}v_0 \\ v_0\end{bmatrix} = 0
$$

$$
det(\begin{bmatrix} -1-\lambda & 2 \\ 2 & -1-\lambda \end{bmatrix}) = (-1-\lambda)^2 + 4
$$

$$(-1)^2 - \lambda^2 + 4$$

$$-\lambda^2 + 5$$

$$-\lambda^2 + 5 = 0 \implies \lambda=-2.2360 \land \lambda = 2.2360$$

$$\begin{bmatrix} -1-2.2360& 2 \\ 2 & -1-2.2360 \end{bmatrix}v=0$$

$$\begin{bmatrix} -3.2360& 2 \\ 2 & -3.2360 \end{bmatrix}v=0$$

$$\begin{bmatrix} -3.2360& 2 \\ 2 & -3.2360 \end{bmatrix}
\begin{bmatrix} v_0 \\ v_1 \end{bmatrix}
=0$$

In [14]:
np.set_printoptions(suppress=True)

AlI = np.array([[-3.236, 2],[2,-3.236]])
print(AlI)
AlI[0, :] = (1/-3.236) * AlI[0, :] 
print(AlI)
AlI[1, :] += -2 * AlI[0, :] 
print(AlI)
AlI[1, :] = (1/AlI[1, :][1]) * AlI[1, :] 
print(AlI)

print(np.eye(2))

[[-3.236  2.   ]
 [ 2.    -3.236]]
[[ 1.         -0.61804697]
 [ 2.         -3.236     ]]
[[ 1.         -0.61804697]
 [ 0.         -1.99990606]]
[[ 1.         -0.61804697]
 [-0.          1.        ]]
[[1. 0.]
 [0. 1.]]


$$ I_2 v = 0 \implies v=\begin{bmatrix}-1 \\ 1 \end{bmatrix}$$