# Handin 4
   ### Andreas Malthe Henriksen ( 202004107 )

Behold the vectors

$$
v_0=\begin{bmatrix}
1 \\ -1 \\ 1 \\ -1
\end{bmatrix}
,
v_1=\begin{bmatrix}
1 \\ 1 \\ 1 \\ 1
\end{bmatrix}
,
v_2=\begin{bmatrix}
2 \\ 0 \\ -2 \\ 0
\end{bmatrix}
$$

### (a) Create the Gram matrix and confirm the set of vectors are orthagonal

First I will represent the vectors in python

In [1]:
import numpy as np

v0 = np.array([1., -1.,  1., -1.])
v1 = np.array([1.,  1.,  1.,  1.])
v2 = np.array([2.,  0., -2.,  0.])

Then we will create a matrix $V$ of these vectors

In [2]:
V = np.array([v0,v1,v2]).T # transpose it to keep vectors in columns
print("Vector matrix V")
print(V)

Vector matrix V
[[ 1.  1.  2.]
 [-1.  1.  0.]
 [ 1.  1. -2.]
 [-1.  1.  0.]]


The Gram matrix is then
$$G = V^TV$$
Which we can find in python like so

In [3]:
G = V.T@V
print("The gram matrix, G")
print(G)

The gram matrix, G
[[4. 0. 0.]
 [0. 4. 0.]
 [0. 0. 8.]]


To check orthogonality between the vectors we will do the following assertions

$$v \cdot u =0,\ \ \forall v, u \in \{v_0,v_1,v_2\} \land v\neq u$$

In [4]:
assert v0.dot(v1) == 0.
assert v0.dot(v2) == 0.
assert v1.dot(v0) == 0.
assert v1.dot(v2) == 0.
assert v2.dot(v0) == 0.
assert v2.dot(v1) == 0.

Since none of the assertions raises any error, all of the vectors must be orthagonal

### (b) Make the projection along $v_0,v_1,v_2$ with

$$Px=\begin{bmatrix}3.0\\ 2.0 \\ 1.0 \\ 0.0\end{bmatrix}$$

The projection we will define as 
$$Pr_x=\frac{Px\cdot v_x}{||v_x||^2_2}v_x$$
The following snippet will be a function that will take $Px$ and project it along a vector $v_x$

In [11]:
def project(vx):
    Px = np.array([3., 2., 1., 0.])
    vxLen = np.linalg.norm(vx)
    return (Px.dot(vx) / vxLen**2) * vx

Now we will use it on each of the vectors to compute the projection

In [14]:
Pr0 = project(v0)
Pr1 = project(v1)
Pr2 = project(v2)

print("Projection along v0")
print(Pr0,"\n")

print("Projection along v1")
print(Pr1,"\n")

print("Projection along v2")
print(Pr2,"\n")

Projection along v0
[ 0.5 -0.5  0.5 -0.5] 

Projection along v1
[1.5 1.5 1.5 1.5] 

Projection along v2
[ 1.  0. -1.  0.] 

