# Handin 4
   ### Andreas Malthe Henriksen ( 202004107 )

Behold the vectors

$$
v_0=\begin{bmatrix}
1 \\ -1 \\ 1 \\ -1
\end{bmatrix}
,
v_1=\begin{bmatrix}
1 \\ 1 \\ 1 \\ 1
\end{bmatrix}
,
v_2=\begin{bmatrix}
2 \\ 0 \\ -2 \\ 0
\end{bmatrix}
$$

### (a) Create the Gram matrix and confirm the set of vectors are orthagonal

First I will represent the vectors in python

In [1]:
import numpy as np

v0 = np.array([1., -1.,  1., -1.])
v1 = np.array([1.,  1.,  1.,  1.])
v2 = np.array([2.,  0., -2.,  0.])

Then we will create a matrix $V$ of these vectors

In [2]:
V = np.array([v0, v1, v2]).T # transpose it to keep vectors in columns
print("Vector matrix V")
print(V)

Vector matrix V
[[ 1.  1.  2.]
 [-1.  1.  0.]
 [ 1.  1. -2.]
 [-1.  1.  0.]]


The Gram matrix is then
$$G = V^TV$$
Which we can find in python like so

In [3]:
G = V.T@V
print("The gram matrix, G")
print(G)

The gram matrix, G
[[4. 0. 0.]
 [0. 4. 0.]
 [0. 0. 8.]]


To check orthogonality between the vectors we will do the following assertions

$$v \cdot u =0,\ \ \forall v, u \in \{v_0,v_1,v_2\} \land v\neq u$$

In [4]:
assert v0.dot(v1) == 0.
assert v0.dot(v2) == 0.
assert v1.dot(v0) == 0.
assert v1.dot(v2) == 0.
assert v2.dot(v0) == 0.
assert v2.dot(v1) == 0.

Since none of the assertions raises any error, all of the vectors must be orthagonal

### (b) Make the projection along $v_0,v_1,v_2$ with

$$x=\begin{bmatrix}3.0\\ 2.0 \\ 1.0 \\ 0.0\end{bmatrix}$$

The projection we will define as $Px$ where $P$ is the matrix
$$P=\sum_{v\ \in\ S}\frac{1}{||v||_2^2}vv^T$$
and where $S$ is the set of vectors 

The following snippet will define $x$ and a function that calculates P from a set of vectors $S$.

In [5]:
np.set_printoptions(suppress=True)
x = np.array([3., 2., 1., 0.])

def P(S, i = 0, acc = 0.):
    if (S.shape[1] <= i): 
        return acc # Finished, out of bounds, return the result
    
    # The current vector and its length vLen squared
    v = S[:, i][:, np.newaxis]
    vLenSq = np.linalg.norm(v)**2
    # Compute the partial sum
    Pv = (1./vLenSq) * (v @ v.T) 
    return P(S, i + 1, acc + Pv) # Recur and accumulate

We will now use the function $P(S)$ to generate the matrix $P$ and compute the projection $Px$

In [6]:
P = P(V)
Px = P@x

print("The matrix P generated from the vector matrix V")
print(P, "\n")

print("The projection Px")
print(Px)

The matrix P generated from the vector matrix V
[[1.  0.  0.  0. ]
 [0.  0.5 0.  0.5]
 [0.  0.  1.  0. ]
 [0.  0.5 0.  0.5]] 

The projection Px
[3. 1. 1. 1.]


### (c) Confirm that $v_3=x-Px$ is orthagonal to $v_0, v_1, v_2$

First lets define $v_3$

In [7]:
np.set_printoptions(suppress=False)
v3 = x - Px
print("v3")
print(v3)

v3
[ 4.44089210e-16  1.00000000e+00 -2.22044605e-16 -1.00000000e+00]


As before we assert that the dot product is $0$, or at least less than the machine error

In [8]:
meps = np.finfo(float).eps

assert v3.dot(v0) <= meps
assert v3.dot(v1) <= meps
#assert v3.dot(v2) <= meps fails!

Although a the python method fails to produce a 0 as the dot product, we can easily confirm this by hand as

$$v_3 \cdot v_2 = v_3v_2^T = 0\cdot 2 + 1\cdot 0 + 0\cdot -2 + -1\cdot 0 = 0$$

Where any value at or under $\epsilon_{machine}$ will be considered to be 0, which here most notably is $v_3$ third entry.

In [9]:
print("Machine Epsilon = ", meps)
print("v3[2] =          ", v3[2])

Machine Epsilon =  2.220446049250313e-16
v3[2] =           -2.220446049250313e-16


Therefore I will consider $v_3$ to be orthagonal to $v_0,v_1,v_2$

### (d) Use the vectors to define a orthonormal basis for $\mathbb{R}^4$

Here i will define the basis B as 
$$B = \begin{bmatrix}v_0(\frac{1}{||v_0||_2})\ |\ v_1(\frac{1}{||v_1||_2})\  |\ v_2(\frac{1}{||v_2||_2})\ |\ v_3(\frac{1}{||v_3||_2})\end{bmatrix}$$

In [10]:
v0Len = np.linalg.norm(v0)
v1Len = np.linalg.norm(v1)
v2Len = np.linalg.norm(v2)
v3Len = np.linalg.norm(v3)

B = np.array([v0*(1/v0Len),v1*(1/v1Len),v2*(1/v2Len),v3*(1/v3Len)]).T

In [11]:
print(B.T@B)
np.set_printoptions(suppress=True)
print("Print with suppressed notation")
print(B.T@B)

[[1.00000000e+00 0.00000000e+00 0.00000000e+00 1.11022302e-16]
 [0.00000000e+00 1.00000000e+00 0.00000000e+00 1.11022302e-16]
 [0.00000000e+00 0.00000000e+00 1.00000000e+00 3.33066907e-16]
 [1.11022302e-16 1.11022302e-16 3.33066907e-16 1.00000000e+00]]
Print with suppressed notation
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


Since all the non-0 entries are either very close to epsilon or 1. I will consider the matrix B to be a basis orthonormal basis for $\mathbb{R}^4$.

The reasoning being, that a orthonormal collection in $\mathbb{R}^4$ with exactly 4 vectors is a orthonormal basis for $\mathbb{R}^4$. Since a collection of vectors are orthonormal if and only if the Grammian, $B^TB$, is equal to the identity matrix, the matrix $B$ must be a orthonormal basis.