#### Exercise 3.1

Let
    
    s=2, t=3, A=([2,1,-1],[0,2,5]), B=([1,-1,0],[0,1,-1])
For the following, decide what are legal operations, which aren't and why, and the resulting value if valid.

    a) sB
    b) A+tB
    c) A^T
    d) A^T+sB
    e) sA^T-tB^T
    f) AB
    g) BA
    h) A^T * B
    i) sAB^T
    j) BA^T * Bt

In [1]:
import numpy as np
s = 2; t = 3
A = np.array([[2,1,-1],[0,2,5]])
B = np.array([[1,-1,0],[0,1,-1]])

# a) Valid scalar multiplication
result = s*B
print ("a) -> \n" , result)

# b) Valid matrix addition and scalar multiplication
result = (A+t*B)
print ("b) -> \n" , result)

# c) Valid transposing
result = (A.T)
print ("c) -> \n" , result)

# d) Invalid, because A^T and sB doesn't match in dimensions
# result = (A.T + (s*B)) Produces error
print ("d) -> " , "ERROR")

# e) Valid scalar multiplication and addition of equal dimension matrices
result = s*A.T+t*B.T
print ("e) -> \n" , result)

# f) Invalid. The matrices' dimensions are not compatible.
# result = np.dot(A,B) Error!
print ("f) -> \n" , "ERROR")

# g) Invalid. The matrices' dimensions are not compatible.
# result = np.dot(B,A) Error!
print ("g) -> \n" , "ERROR")

# h) Valid. The matrices' dimensions are compatible.
result = np.dot(A.T,B)
print ("h) -> \n" , result)

# i) Valid. The matrices' dimensions are compatible. And scalar multiplication
result = s*np.dot(A,B.T)
print ("i) -> \n" , result)

# j) Valid. The matrices' dimensions are compatible. And scalar multiplication
result = np.dot(np.dot(B,A.T), B*t) # BA^T * Bt
print ("j) -> \n" , result)

a) -> 
 [[ 2 -2  0]
 [ 0  2 -2]]
b) -> 
 [[ 5 -2 -1]
 [ 0  5  2]]
c) -> 
 [[ 2  0]
 [ 1  2]
 [-1  5]]
d) ->  ERROR
e) -> 
 [[ 7  0]
 [-1  7]
 [-2  7]]
f) -> 
 ERROR
g) -> 
 ERROR
h) -> 
 [[ 2 -2  0]
 [ 1  1 -2]
 [-1  6 -5]]
i) -> 
 [[ 2  4]
 [-4 -6]]
j) -> 
 [[  3  -9   6]
 [  6 -15   9]]


#### Opgave 3.2
Matrix products are not commutative. What effect could this have on a 3 dimensional robot arm?
    
    Dunno

#### Opgave 3.3
Build the neighbour matrix (or edge matrix)

In [2]:
A = np.array([
    [0,1,0,1,0,0,0,0,0,0],
    [1,0,1,0,0,0,0,0,0,0],
    [0,1,0,1,1,0,0,0,0,0],
    [1,1,1,0,0,0,1,0,0,0],
    [0,0,1,0,0,1,0,0,0,1],
    [0,0,0,0,1,0,1,0,1,1],
    [0,0,0,1,0,1,0,0,0,0],
    [0,0,0,0,0,0,0,0,1,0],
    [0,0,0,0,0,1,0,1,0,1],
    [0,0,0,0,1,1,0,0,1,0]
])

    a) how many paths of length 2 to C_5?
    b) how many paths of length 2 to C_7?
    c) Which computers cannot be reached from C_9 with at most 3 steps?
    d) Are there any computers that is unreachable from C_0 in 5 steps?

In [3]:
print ("a)-> " , np.dot(A,A)[:,5].sum())

a)->  11


In [4]:
print ("b)-> " , np.dot(A,A)[:,7].sum())

b)->  3


In [5]:
print ("c)-> " , np.dot(A,np.dot(A,A))[:,9])

c)->  [0 1 1 2 6 6 2 1 6 4]


In [7]:
print ("d)-> " , np.dot(np.dot(np.dot(np.dot(A,A),A),A),A)[0,:])
print("No zeroes means theres always at least one")

d)->  [ 9 22 11 26 16 12  4  1  5  5]
No zeroes means theres always at least one
